# paths
dataset_path: './data/ast_traversal/'
model_path: './model/'
model_log_path: './experiments/'

train_dataset: 
  'SRC': 
    'src-train.txt'
  'TGT': 
    'tgt-train.txt'  
eval_dataset: 
  'SRC': 
    'src-val.txt'
  'TGT':
    'tgt-val.txt'


# logging and saving options
log_run_name: 'test_gpu_run'
save_logs: False
save_model: True
verbose: True

# data processing parameters
custom_tokenization: False
src_min_token_count: 0
src_max_token_freq: 1
tgt_min_token_count: 0
tgt_max_token_freq: 1

# model parameters
embedding_size: 75
hidden_size: 100
embedding_size: 150
embedding_dropout: 0.0

# train/eval parameters
learning_rate: .003 
max_epoch: 10
batch_size: 32
seed: 42
metric: None
device: 'cuda'
