# paths
dataset_path: './data/conala/'
model_path: './model/'
model_log_path: './experiments/'

train_dataset: 
  'SRC': 
    'src-train.csv'
  'TGT': 
    'tgt-train.csv'  
eval_dataset: 
  'SRC': 
    'src-val.csv'
  'TGT':
    'tgt-val.csv'


# logging and saving options
log_run_name: 'metric_test'
save_logs: False
save_model: False
verbose: True

# data processing parameters
custom_tokenization: True
src_min_token_count: 3
src_max_token_freq: 1
tgt_min_token_count: 5
tgt_max_token_freq: 1

# model parameters
embedding_size: 256
hidden_size: 100
embedding_dropout: 0.8

# train/eval parameters
learning_rate: .003 
max_epoch: 10
batch_size: 256
seed: 42
metric: None
device: 'cuda'
