# paths
dataset_path: './data/'
model_path: './model/'
model_log_path: './experiments/'

train_dataset: 
  'SRC': 
    'src-train.txt'
  'TGT': 
    'tgt-train.txt'

  
eval_dataset: 
  'SRC': 
    'src-val.txt'
  'TGT':
    'tgt-val.txt'


# logging and saving options
log_run_name: 'test_run_with_tokenizer'
save_logs: False
save_model: True
verbose: True

# model hyperpaprameters
learning_rate: .003 
max_epoch: 10
batch_size: 32
seed: 42
embedding_size: 50
hidden_size: 50
embedding_dropout: 0.0