# paths
dataset_path: './data/conala/'
model_path: './model/'
model_log_path: './experiments/'

train_dataset: 
  'SRC': 
    'src-train.csv'
  'TGT': 
    'tgt-train.csv'

  
eval_dataset: 
  'SRC': 
    'src-eval.csv'
  'TGT':
    'tgt-eval.csv'


# logging and saving options
log_run_name: 'conala_model'
save_logs: False
save_model: True
verbose: True

# model hyperpaprameters
learning_rate: .003 
max_epoch: 3
batch_size: 32
seed: 42
embedding_size: 100
hidden_size: 100
embedding_dropout: 0.0
metric: None